# Generated by Django 2.2.12 on 2020-10-30 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shorts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.IntegerField()),
                ('rate', models.CharField(max_length=10)),
                ('short', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'shorts',
            },
        ),
    ]
